### ISSUE TITLE
Ritual success `probability` and negative effects

### ISSUE THREAD

**Issue by reicheltp** [reicheltp/mc-celtic-rituals#49]
The success of some rituals depends on the skills of the player and the conditions around.

## Requirements
- [ ] A ritual can fail with a specified probability
- [ ] If a ritual fail, negative effects apply
- [ ] Per default rituals do not have a chance to failure

## TODO
TBD
